### ISSUE TITLE
Feature Request: Block Outline Helpers (base code supplied)

### ISSUE THREAD

**Issue by broken8** [godaddy/coblocks#1103]
I need to suggest a subtle and very simple styles addition to the block editor. I've been using it for a few months and found it tremendously useful. I call them "block outline helpers"! I've put up a gist [here](https://gist.github.com/broken8/f0644c3eebc3ef63706a1facc51bc9b1) with the basic code. Images speak faster that typing. You can see what it adds to the editor below.

![Block+Outline+Helpers+Demo](https://user-images.githubusercontent.com/38085966/68440970-897b5300-01c4-11ea-90cd-08dba08533a8.gif)

I'm sure you guys could add it as a toggle in the inspector and style it differently. Editors Kit has an even simpler box outline implementation but I hope you agree, this is in a different league.

**Comment by AnthonyLedesma** [comment]
Hi @broken8,

I took the time to implement the outline helpers so I could get an idea for how your request would function. I think in some ways this in an interesting idea but ultimately a feature like this is outside-of-scope of CoBlocks. At this time our development team is not looking to implement this feature. 

CoBlocks is focused on the page building where your request might be considered an improvement to Gutenberg Core. Since this feature better fits with Gutenberg I suggest you make a feature request like this on the Gutenberg GutHub. 

Thank you for taking time to share your ideas and to contribute to CoBlocks. While we are not pursuing this idea know that your contributions are both appreciated and welcomed.

Regards,

Anthony

**Comment by broken8** [comment]
Hi @AnthonyLedesma,

Thanks for taking the time. No worries. I appreciate your suggestions. It needs some refining, anyway. Then perhaps I'll approach Gutenberg.

Cheers.
