### ISSUE TITLE
Add responsive font sizes

### ISSUE THREAD

**Issue by phpbits** [godaddy/coblocks#369]
It would be really awesome if we could do responsive font sizes the same way we are doing responsive sizes on shape divider. Would be really challenging but I think it'll worth it :)

**Comment by richtabor** [comment]
Yes! I think this is a great idea. It's definitly a tricky ask. Let's work on this after 2.0 releases. 💪

**Comment by phpbits** [comment]
@richtabor Yeah, I've created a hero section and would love to change the font sizes on mobile version. I think we can pull this off too but yeah after 2.0 💯 

![Uploading Screen Capture on 2019-02-26 at 20-43-27.gif…]()

**Comment by EvanHerman** [comment]
Doesn't this fallback more on the theme itself as opposed to CoBlocks?

**Comment by richtabor** [comment]
@EvanHerman, yes - at least for the FontSizePicker component (where themes set the classes/sizes). This issue was originally geared towards the Typography Panel (screenshot below). Perhaps figuring a way to add the same type of control for font-size, as we see in the core Paragraph block (which could be easily manipulated theme-side for responsive fonts. 

<img width="524" alt="Screen Shot 2019-06-26 at 10 10 15 AM" src="https://user-images.githubusercontent.com/1813435/60187004-d4d72b00-97fa-11e9-85d1-9845f14795ab.png">
