### ISSUE TITLE
The Image ToggleControl setting is not saving in the Menu Item block

### ISSUE THREAD

**Issue by richtabor** [godaddy/coblocks#610]
**Describe the bug**
Toggling to display an image within a Menu Item block does not save unless an image is actually uploaded.

![ScreenFlow](https://user-images.githubusercontent.com/1813435/60219187-96179400-983f-11e9-988c-9a15528c8445.gif)

**Comment by jrtashjian** [comment]
This was an intentional behavior I left in place. To prevent polluting the post_content with saved attributes in the block comment, I decided to pull the status of that toggle based on the existence of an image. Same behavior exists on the ToggleControl for prices. Although, I am realizing the parent block showImages and showPrices attribute is persisted there.

Do we want to persist this so that it's always showing the placeholders if they clicked showImages/Prices? Or does it make sense to read from the HTML and set it from that? We can go either way, I'm just unsure what the user would expect.

**Comment by richtabor** [comment]
In my opinion, if the parent block saves the "Images" setting, then so should the child blocks.
