### ISSUE TITLE
Second Food Item placeholder disappears with zero state

### ISSUE THREAD

**Issue by onuro** [godaddy/coblocks#617]
**Describe the bug**
Hey guys, great new Food & Drinks block, kudos! Now when I first insert the block and escape click on the inner blocks, one of the items disappear and doesn't come back.

**Update:** 
It does actually come back when I start entering content on the first menu item, but that was confusing as a user. Maybe it would be easier to use an appender instead for adding a new item, or a helper indicating that I will be able to add more. Expecting me to start typing on the first menu item to be able to see the second menu item was unexpected :)

**To Reproduce**

1. Insert a new food & drinks block
2. Click on the first menu item
3. See second menu item vanish! :)

**Screenshots**
![foodblock](https://user-images.githubusercontent.com/645713/60336216-6f28a180-99a8-11e9-8be3-2f91d201306e.gif)

**Isolating the problem:**
- [* ] This bug happens with no other plugins activated
- [* ] This bug happens with and without the Gutenberg plugin active
- [* ] I can reproduce this bug consistently using the steps above

**WordPress Environment**

<details>

- Wordpress 5.2.2
- Gutenberg 6.0

</details>

**Comment by jrtashjian** [comment]
Thanks @onuro!

I think the solution here would be to ensure at least two placeholders exist when there are only empty blocks present in the parent. We are already making this check to ensure at least one placeholder exists at all times and any extras are removed (which is why this is happening). We just need to refine our algorithm for it.
